version: 1.0.{build}
os: Visual Studio 2017
test: off
clone_folder: C:\projects\libigl
branches:
  only:
    - master
    - dev
environment:
  BOOST_ROOT: C:/Libraries/boost_1_65_1
install:
  - git submodule update --init --recursive
  - cinstall: python
build_script:
  - cd c:\projects\libigl
  # External libraries (boost)
  # - cd external
  # - mkdir build
  # - cd build
  # - cmake -G "Visual Studio 15 2017 Win64" -T "host=x64" ..
  # - msbuild %MSBuildOptions% libigl_external.sln
  # - cd ../..
  # Python bindings
  # - cd python
  # - mkdir build
  # - cd build
  # - cmake -DLIBIGL_WITH_EMBREE=OFF -DLIBIGL_USE_STATIC_LIBRARY=ON ../
  # - msbuild %MSBuildOptions% pyigl.sln
  # - cd ../tutorial
  # - ${PYTHON} 101_FileIO.py
  # - cd ../../
  # Tutorials and tests
  - mkdir build
  - cd build
  - cmake -DLIBIGL_BUILD_TESTS=OFF -DLIBIGL_BUILD_TUTORIALS=ON -DLIBIGL_BUILD_PYTHON=OFF -G "Visual Studio 15 2017 Win64" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=Debug /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% libigl.sln
